//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by CodeSmith Template.
//     Creater: dylan
//     Date:    2018/3/15 9:15
//     Version: 2.0.0.0
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Chloe.Entity;

namespace ConsoleApp8
{
    /// <summary>
    /// 会员主表Mem_MemberAccount
    /// </summary>
    [TableAttribute("Mem_MemberAccount", ConfigName = "WALIUJR_MEMBER")]
    public class Mem_MemberAccount
    {

        [ColumnAttribute(Name = "MemberID", IsPrimaryKey = true)]
        /// <summary>
        /// 会员ID.
        /// </summary>
        public int? MemberID { get; set; }

        /// <summary>
        /// 用户名.
        /// </summary>
        [ColumnAttribute(Name = "MemberName")]
        public string MemberName { get; set; }


        /// <summary>
        /// 会员KEY.
        /// </summary>
        public Guid? MemberKey { get; set; }

        /// <summary>
        /// 密码.
        /// </summary>
        public string Password { get; set; }

        /// <summary>
        /// 支付密码.
        /// </summary>
        public string PayPassword { get; set; }

        /// <summary>
        /// 昵称.
        /// </summary>
        public string NickName { get; set; }

        /// <summary>
        /// 真实姓名.
        /// </summary>
        public string TrueName { get; set; }

        /// <summary>
        /// 姓别.
        /// </summary>
        public int? SexType { get; set; }

        /// <summary>
        /// 生日.
        /// </summary>
        public string Birthday { get; set; }

        /// <summary>
        /// 会员类型（普通会员：1，理财师：4）.
        /// </summary>
        public int? MemberType { get; set; }

        /// <summary>
        /// 会员等级.
        /// </summary>
        public int? MemberLevel { get; set; }

        /// <summary>
        /// 一句话介绍.
        /// </summary>
        public string ShortIntroduction { get; set; }

        /// <summary>
        /// 省编码.
        /// </summary>
        public string ProvinceCode { get; set; }

        /// <summary>
        /// 市编码.
        /// </summary>
        public string CityCode { get; set; }

        /// <summary>
        /// .
        /// </summary>
        public string AreaCode { get; set; }

        /// <summary>
        /// 区域CODE.
        /// </summary>
        public string AreaCodePath { get; set; }

        /// <summary>
        /// 区域名称.
        /// </summary>
        public string AreaNamePath { get; set; }

        /// <summary>
        /// 区域地址.
        /// </summary>
        public string AreaAddress { get; set; }

        /// <summary>
        /// 状态：0=禁用，4=正常.
        /// </summary>
        public int? StatusFlag { get; set; }

        /// <summary>
        /// 禁用原因.
        /// </summary>
        public string DisableReason { get; set; }

        /// <summary>
        /// 注册IP.
        /// </summary>
        public string RegistIp { get; set; }

        /// <summary>
        /// 图像.
        /// </summary>
        public string Logo { get; set; }

        /// <summary>
        /// 手机.
        /// </summary>
        public string Mobile { get; set; }

        /// <summary>
        /// 手机验证；0=未验证，1=已验证.
        /// </summary>
        public bool? MobileFlag { get; set; }

        /// <summary>
        /// 手机验证时间.
        /// </summary>
        public DateTime? MobileVerifyTime { get; set; }

        /// <summary>
        /// 邮箱.
        /// </summary>
        public string Email { get; set; }

        /// <summary>
        /// 邮件是否验证：0=未验证，1=已验证.
        /// </summary>
        public bool? EmailFlag { get; set; }

        /// <summary>
        /// 邮箱验证时间.
        /// </summary>
        public DateTime? EmailVerifyTime { get; set; }

        /// <summary>
        /// QQ.
        /// </summary>
        public string QQ { get; set; }

        /// <summary>
        /// WeChat.
        /// </summary>
        public string WeChat { get; set; }

        /// <summary>
        /// 上次登录时间.
        /// </summary>
        public DateTime? BeforeLoginTime { get; set; }

        /// <summary>
        /// 最后登录时间.
        /// </summary>
        public DateTime? LastLoginTime { get; set; }

        /// <summary>
        /// 最后登录IP.
        /// </summary>
        public string LastLoginIp { get; set; }

        /// <summary>
        /// 登录次数.
        /// </summary>
        public int? LoginTimes { get; set; }

        /// <summary>
        /// 设备来源：0=未设备，1=PC，2=安卓，3=IOS.
        /// </summary>
        public int? EquipmentSource { get; set; }

        /// <summary>
        /// 渠道来源：自然渠道=1，QQ渠道=2，Weibo渠道=4，微信渠道=6，支付宝渠道=8.
        /// </summary>
        public int? ChannelSource { get; set; }

        /// <summary>
        /// 创建时间.
        /// </summary>
        public DateTime? CreateTime { get; set; }

        /// <summary>
        /// 备注.
        /// </summary>
        public string Remark { get; set; }

        /// <summary>
        /// 是否签署认定.
        /// </summary>
        public bool? IsCognizance { get; set; }

        /// <summary>
        /// 邀请人.
        /// </summary>
        public int? InviterID { get; set; }

        /// <summary>
        /// 用户运营类型标识.
        /// </summary>
        public int? MemberFlag { get; set; }

        /// <summary>
        /// 首次登录的设备型号.
        /// </summary>
        public string FirstLoginEquipment { get; set; }
    }
}


