////------------------------------------------------------------------------------
//// <autogenerated>
////     This code was generated by CodeSmith Template.
////     Creater: dylan
////     Date:    2018/3/14 17:02
////     Version: 2.0.0.0
////     Changes to this file may cause incorrect behavior and will be lost if
////     the code is regenerated.
//// </autogenerated>
////------------------------------------------------------------------------------

//using System;
//using System.Collections.Generic;
//using SqlSugar;
//namespace ConsoleApp8
//{
//    /// <summary>
//    /// student info
//    /// </summary>
//    [SugarTable("Student")]
//    public class Student
//    {
//        /// <summary>
//        /// Pk.
//        /// </summary>
//        [SugarColumn(ColumnName = "Id", IsPrimaryKey = true, IsIdentity = true)]
//        public int? Id { get; set; }

//        /// <summary>
//        /// .
//        /// </summary>
//        public int? SchoolId { get; set; }

//        /// <summary>
//        /// Student Name.
//        /// </summary>
//        public string Name { get; set; }

//        /// <summary>
//        /// .
//        /// </summary>
//        public DateTime? CreateTime { get; set; }
//    }
//}


